add Readme and DES
xnd0/No-Rona_App pull request #10
Opened 2022-06-13 22:23 UTC by zzcipod

Add readme, title, des

2022-06-13 22:27 UTC, xnd0 approved these changes
No Readme.md actually added. Please add

2022-06-13 23:21 UTC, xnd0 requested changes
No Readme.md file actually added, please add.

2022-06-14 19:33 UTC, zzcipod commented
ok

2022-06-14 19:34 UTC, zzcipod reviewed
ok

2022-08-06 17:33 UTC, closed without merging